AWSTemplateFormatVersion: '2010-09-09'
Description: 'Riigikogu Radar - Parliamentary Intelligence Platform'

Parameters:
  InstanceType:
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    Description: EC2 instance type

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of existing EC2 KeyPair for SSH access

  MongoDBUri:
    Type: String
    NoEcho: true
    Description: MongoDB Atlas connection string

  AnthropicApiKey:
    Type: String
    NoEcho: true
    Description: Anthropic API key for Claude

  VoyageApiKey:
    Type: String
    NoEcho: true
    Description: Voyage AI API key for embeddings

Resources:
  # Security Group
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Riigikogu Radar security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH access
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
          Description: Next.js dev server
      Tags:
        - Key: Name
          Value: riigikogu-radar-sg

  # IAM Role for EC2
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: riigikogu-radar-role

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  # EC2 Instance
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !FindInMap [RegionAMI, !Ref 'AWS::Region', AMI]
      SecurityGroupIds:
        - !Ref SecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          # Log output
          exec > >(tee /var/log/user-data.log) 2>&1

          echo "=== Riigikogu Radar Setup Starting ==="

          # Update system
          apt-get update && apt-get upgrade -y

          # Install Node.js 20
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs git build-essential

          # Create app user
          useradd -m -s /bin/bash riigikogu || true

          # Clone repository
          cd /home/riigikogu
          sudo -u riigikogu git clone https://github.com/AivarStig/riigikogu-radar.git || true
          cd riigikogu-radar

          # Install dependencies
          sudo -u riigikogu npm ci

          # Create .env file
          cat > .env << 'ENVEOF'
          MONGODB_URI=${MongoDBUri}
          ANTHROPIC_API_KEY=${AnthropicApiKey}
          VOYAGE_API_KEY=${VoyageApiKey}
          ENVEOF
          chown riigikogu:riigikogu .env
          chmod 600 .env

          # Create systemd service for Next.js
          cat > /etc/systemd/system/riigikogu-radar.service << 'SERVICEEOF'
          [Unit]
          Description=Riigikogu Radar Next.js App
          After=network.target

          [Service]
          Type=simple
          User=riigikogu
          WorkingDirectory=/home/riigikogu/riigikogu-radar
          ExecStart=/usr/bin/npm run start
          Restart=on-failure
          RestartSec=10
          Environment=NODE_ENV=production
          Environment=PORT=3000

          [Install]
          WantedBy=multi-user.target
          SERVICEEOF

          # Create daily sync timer
          cat > /etc/systemd/system/riigikogu-sync.service << 'SYNCEOF'
          [Unit]
          Description=Riigikogu Radar Daily Sync
          After=network.target

          [Service]
          Type=oneshot
          User=riigikogu
          WorkingDirectory=/home/riigikogu/riigikogu-radar
          ExecStart=/usr/bin/npx tsx scripts/sync-api.ts all
          ExecStartPost=/usr/bin/npx tsx scripts/generate-embeddings.ts
          Environment=NODE_ENV=production
          SYNCEOF

          cat > /etc/systemd/system/riigikogu-sync.timer << 'TIMEREOF'
          [Unit]
          Description=Run Riigikogu sync daily at 5am UTC

          [Timer]
          OnCalendar=*-*-* 05:00:00
          Persistent=true

          [Install]
          WantedBy=timers.target
          TIMEREOF

          # Build the app
          cd /home/riigikogu/riigikogu-radar
          sudo -u riigikogu npm run build

          # Enable and start services
          systemctl daemon-reload
          systemctl enable riigikogu-radar
          systemctl enable riigikogu-sync.timer
          systemctl start riigikogu-radar
          systemctl start riigikogu-sync.timer

          echo "=== Setup Complete ==="
      Tags:
        - Key: Name
          Value: riigikogu-radar

Mappings:
  RegionAMI:
    us-east-1:
      AMI: ami-0c7217cdde317cfec  # Ubuntu 22.04 LTS
    us-west-2:
      AMI: ami-03f65b8614a860c29
    eu-west-1:
      AMI: ami-0905a3c97561e0b69
    eu-central-1:
      AMI: ami-0faab6bdbac9486fb
    eu-north-1:
      AMI: ami-0014ce3e52359afbd  # Stockholm - closest to Estonia

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref Instance

  PublicIP:
    Description: Public IP address
    Value: !GetAtt Instance.PublicIp

  PublicDNS:
    Description: Public DNS name
    Value: !GetAtt Instance.PublicDnsName

  SSHCommand:
    Description: SSH command to connect
    Value: !Sub 'ssh -i ${KeyName}.pem ubuntu@${Instance.PublicIp}'

  AppURL:
    Description: Application URL
    Value: !Sub 'http://${Instance.PublicIp}:3000'
